### ISSUE TITLE
Arduino wiring with piezo sensor

### ISSUE THREAD

**Issue by stringhigh** [LuiCat/ArduinoTaikoController#3]
I have a question about sensor connection
As far as I know, when connecting piezo sensor to arduino board, the red wire(+) should go to analog pin or digital pin, and the black wire(-) should connected to GND.
I might be wrong, I'm not an expert about arduino. just want to know if the drawing has some mistake or not.

**Comment by LuiCat** [comment]
Hi stringhigh, nice to have you asking!

Although you might be confused with the sensor connection in the instruction, but it comes with reasons. Hope you won't be frustrated.

The thing is, piezo sensors actually produce a signal ranging from a minus voltage to a positive voltage. This is like the sound wave. At least it's sure that piezo sensors does not simply serves as a mechanical switch.

Now given this situation, if we connect the sensor to GND, then at the analog pin we would get negative voltages, which may harm the chip. On my side, if I hit the drum too hard, my Arduino temporarily disconnect from my computer. By connecting to 3.3v, we effectively "biased" the input voltage for a more usable range (since Leonardo is a 5v board).

As for the + and - of the sensor, it doesn't really matter which goes into which pin. My code deals the signal in a way that both positive and negative input are effective.

Anyway, wish you good luck with your drum controller!

**Comment by stringhigh** [comment]
Thank you for reply. now I get to know more about piezo :)
